// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RankingCovid19.Data.Context;

namespace RankingCovid19.Data.Migrations
{
    [DbContext(typeof(Covid19SummaryContext))]
    [Migration("20200530153308_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RankingCovid19.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("RankingCovid19.Domain.Entities.Country", b =>
                {
                    b.OwnsMany("RankingCovid19.Domain.Entities.Covid19Ranking", "Summaries", b1 =>
                        {
                            b1.Property<Guid>("CountryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("ActiveCases")
                                .HasColumnType("bigint");

                            b1.Property<long>("FatalCases")
                                .HasColumnType("bigint");

                            b1.Property<int>("RankingPosition")
                                .HasColumnType("int");

                            b1.Property<long>("RecoveredCases")
                                .HasColumnType("bigint");

                            b1.HasKey("CountryId");

                            b1.ToTable("Covid19Ranking");

                            b1.WithOwner()
                                .HasForeignKey("CountryId")
                                .HasConstraintName("FK_Countries");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
